/*
 * Amazon FreeRTOS
 * Copyright (C) 2018 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * http://aws.amazon.com/freertos
 * http://www.FreeRTOS.org
 */
#ifndef _AWS_TLS_TEST_H_
#define _AWS_TLS_TEST_H_
#if 1 //iot OTA
/*
* PEM-encoded client certificate.
*
* Certificate for P-256 elliptic curve key.
*/

static const char tlstestCLIENT_CERTIFICATE_PEM_EC[] = "-----BEGIN CERTIFICATE-----\n"
"MIICtjCCAZ6gAwIBAgIVAJ/BDrkMmwCP1qwX+XEUlhmTSlFsMA0GCSqGSIb3DQEB\n"
"CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t\n"
"IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0xOTA0MTgwOTQy\n"
"MTJaFw00OTEyMzEyMzU5NTlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21l\n"
"LVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwWTATBgcq\n"
"hkjOPQIBBggqhkjOPQMBBwNCAARg7rWYk4B5+tQd9kc9Ibo9hVFAQsHj4gez9M51\n"
"HRdwbbd2CDYl5O8cpLrP/v4nsfQ2ANCKn/JCgtJUq9zbKPYto2AwXjAfBgNVHSME\n"
"GDAWgBTDv/moHkkZYmU6U43jZGcBXMZ6WzAdBgNVHQ4EFgQUjJgbGrMFQrDeZXCs\n"
"JEvdWUWIMsgwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcN\n"
"AQELBQADggEBALrcM3sxQ6KmkRCIhPokz7A5Eh69sHrUcof1tjBg0tVc8fuY4oZA\n"
"E09Frn7kpHS5f/+lsdVUwJyFWUaGv/0RrT4BuKZYV6rDerZNMOyEzd+dzLSGIHLH\n"
"taiK+3MujeCB4p5dzsYSp2Oixazk5KRYHWsLQf/EtwfWen3XMtgyAPI3NqRB7Fu5\n"
"oB3nG5okfIs/wO1atsWE8clskrUNNaNPqjS79YJ46/4XWvI5EeaKz+hfTh1N+dyV\n"
"Sg2WqOA7IVfslsMpfsmVQJAacJfeLKGfJlXqQswmm7BOHUBwhJhnnW137sLG0QTM\n"
"vJ50U5WrAjg/OAXVTUuIOoae6jo72fdsc+M=\n"
"-----END CERTIFICATE-----";

/*
* PEM-encoded client private key.
*
* This is a P-256 elliptic curve key.
*/

static const char tlstestCLIENT_PRIVATE_KEY_PEM_EC[] = "-----BEGIN EC PRIVATE KEY-----\n"
"MHcCAQEEIJvAWBJei8wdSwBlpuYFH1l2+FmFbpkRQVH6Oz+fp5s4oAoGCCqGSM49\n"
"AwEHoUQDQgAEYO61mJOAefrUHfZHPSG6PYVRQELB4+IHs/TOdR0XcG23dgg2JeTv\n"
"HKS6z/7+J7H0NgDQip/yQoLSVKvc2yj2LQ==\n"
"-----END EC PRIVATE KEY-----";

/* One character of this certificate has been changed in the issuer
 * name from Amazon Web Services to Amazon Web Cervices. */
static const char tlstestCLIENT_CERTIFICATE_PEM_MALFORMED[] = "-----BEGIN CERTIFICATE-----\n"
"MIIDWjCCAkKgAwIBAgIVAMoxHqvpzJEho9TH5p/RG2Sa8bCKMA0GCSqGSIb3DQEB\n"
"CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgQ2VydmljZXMgTz1BbWF6b24uY29t\n"
"IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0xOTAzMjgwODUx\n"
"MzhaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh\n"
"dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDzror42EqPVW/H9NZ8\n"
"UEuJ3RFWB36WEJXbyRvBIZmGcYkz5rGPFro5omNdU5usNylMqEJp5wkT4EF0SCp4\n"
"T8a4K6hgV7jjn1mBYSspEa0NjDU/wNbdGq6K7VK5fNsiozFMK5daktxcriK7ni3q\n"
"4/XtlOLd4Klszf+TlMZZ8CJoAJ6WE9TW58XUqWhxdvJAgj9PAAarCvLxXUQM6Bi6\n"
"K0ZDOY22RuKSKJZLGOk//Q9E6JWFdXOCzWo8wJ9t5o122r8RGdK2zzP9b+QjZ8rD\n"
"XIdwFLT2w8EgNKmO+TKYKfmTdw4ljBWl3NzYBNpiR5fOdcGNuIGbrwbfpl3dq24C\n"
"/AqfAgMBAAGjYDBeMB8GA1UdIwQYMBaAFKfKMHEn1eZasCkL28yq//CZicvZMB0G\n"
"A1UdDgQWBBT/BrWXVCgj7J40dSAnXORD9ecbkjAMBgNVHRMBAf8EAjAAMA4GA1Ud\n"
"DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAGSUzdgG1hyhIn+a6vAEqfDH/\n"
"1uWOonEQmc1V9UxGrJf54enr065tNmYyesiWb/RM5RyKKBUb17cI6ZXzixPLs8qr\n"
"K02reTtJ2EpB2mmVXF9yBQpp9xX2+FTH2Y/hnXrA+4BNYiZl/5myRJXaFFvNgscG\n"
"w4vh9WyW6zUIL10fBUde8/hmXmcys6fVfkGtB88biGk1TD5NOffdv3ZKen2JQiRA\n"
"qtQww9iie2KevCzXIhVVL0efJAs+DEg4Dowi2fS+CAbICZQJmg/MxgnHCJtI737V\n"
"Ir9oxW6Txb1fnxLJMa/ZXuIalvpsynqnziKr+5k1QrINMNldOXZ7wPkhc2CagQ==\n"
"-----END CERTIFICATE-----";


/* Certificate which is not trusted by the broker. */
static const char tlstestCLIENT_UNTRUSTED_CERTIFICATE_PEM[] = "-----BEGIN CERTIFICATE-----\n"
"MIIBljCCATwCCQDDKC73p+hTZTAKBggqhkjOPQQDAjBTMQswCQYDVQQGEwJBVTET\n"
"MBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQ\n"
"dHkgTHRkMQwwCgYDVQQDDANhYWEwHhcNMTkwNDE4MTE0NTE5WhcNMjAwODMwMTE0\n"
"NTE5WjBTMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UE\n"
"CgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMQwwCgYDVQQDDANiYmIwWTATBgcq\n"
"hkjOPQIBBggqhkjOPQMBBwNCAASifPjHQJuXlbzSA0kazMDdLwChmZUWQMNRJJOy\n"
"x35imSTZkxCOuEyuKZ3y2ktuQdWRlP5go0YCpYSfTs756tEsMAoGCCqGSM49BAMC\n"
"A0gAMEUCIGs5fCpltG+5cRumaFr9EKOKzkVdcCqYycBzu+8F/5CUAiEAmcsIpXON\n"
"pjiHukmSmqWSfy7x2Mvbj9IvHael/4zzuec=\n"
"-----END CERTIFICATE-----";

/* Private key corresponding to the untrusted certificate. */
static const char tlstestCLIENT_UNTRUSTED_PRIVATE_KEY_PEM[] = "-----BEGIN EC PRIVATE KEY-----\n"
"MHcCAQEEIIGGS+K2c3ABXehdVwOEMSHGdfOZaEdZ6EtMF0k2+PRcoAoGCCqGSM49\n"
"AwEHoUQDQgAEonz4x0Cbl5W80gNJGszA3S8AoZmVFkDDUSSTssd+Ypkk2ZMQjrhM\n"
"rimd8tpLbkHVkZT+YKNGAqWEn07O+erRLA==\n"
"-----END EC PRIVATE KEY-----";

/* Device certificate created using BYOC instructions. */
static const char tlstestCLIENT_BYOC_CERTIFICATE_PEM[] = "-----BEGIN CERTIFICATE-----\n"
"MIIBnjCCAUMCCQCpOKlkwG0pPTAKBggqhkjOPQQDAjBWMQswCQYDVQQGEwJBVTET\n"
"MBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQ\n"
"dHkgTHRkMQ8wDQYDVQQDDAZ4dWVjYWkwHhcNMTkwNDE5MDYyNTQ2WhcNMjAwODMx\n"
"MDYyNTQ2WjBXMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8G\n"
"A1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRAwDgYDVQQDDAdpdnk1NjYx\n"
"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELY1NQshm0WK20TjXDilnuBOTJm9y\n"
"bgIaZVUSFLx5qdTHfnjlOMjCGdodKBoSIJoGuKgk1OAS7F9/MwNuDpHZCzAKBggq\n"
"hkjOPQQDAgNJADBGAiEAwqBUpspMjZmEjnCdcbbbPhk1jgn9vTKM2ceQ94yqCkIC\n"
"IQCwyi6st46WIFOeKWEw1utf8tzqKcd9KxJmFxj354WOqQ==\n"
"-----END CERTIFICATE-----";

/* Device private key created using BYOC instructions. */
static const char tlstestCLIENT_BYOC_PRIVATE_KEY_PEM[] = "-----BEGIN EC PRIVATE KEY-----\n"
"MHcCAQEEIKHLl+gry1m/TNd3rgWhWAu/l6RCKEPO0N8V9ybGz10roAoGCCqGSM49\n"
"AwEHoUQDQgAELY1NQshm0WK20TjXDilnuBOTJm9ybgIaZVUSFLx5qdTHfnjlOMjC\n"
"GdodKBoSIJoGuKgk1OAS7F9/MwNuDpHZCw==\n"
"-----END EC PRIVATE KEY-----";

#else //iot caixue
/*
* PEM-encoded client certificate.
*
* Certificate for P-256 elliptic curve key.
*/

static const char tlstestCLIENT_CERTIFICATE_PEM_EC[] = "-----BEGIN CERTIFICATE-----\n"
"MIIC9jCCAd6gAwIBAgIVAMhrfBctky+K+ZXh8cGZQceDBYjVMA0GCSqGSIb3DQEB\n"
"CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t\n"
"IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0xOTAzMjQxMDMw\n"
"NTdaFw00OTEyMzEyMzU5NTlaMIGEMQswCQYDVQQGEwJDTjEQMA4GA1UECAwHVGlh\n"
"bmppbjEQMA4GA1UEBwwHVGlhbmppbjEPMA0GA1UECgwGdW5pc29jMQwwCgYDVQQL\n"
"DAN3Y24xDzANBgNVBAMMBmNhaXh1ZTEhMB8GCSqGSIb3DQEJARYSeHVlLmNhaUB1\n"
"bmlzb2MuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEqGtFiBzeCj8qOeCZ\n"
"hw3LjS2qbGUpk7kIYM4IzvF20xLEsh8HReU0sbspxQRvs062mkS9RBb6+h5dR36A\n"
"Ekx1daNgMF4wHwYDVR0jBBgwFoAUPWdhLvuC3n2QU0+AaWUZphboBIUwHQYDVR0O\n"
"BBYEFE4e8gtDxeMjy2fH+A1dKxPSv6TxMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/\n"
"BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQBciPNtkNmQ6vUX6khtk9GkiRq8JdYd\n"
"0RMHlqNlq7ZYxEu2OFIMGIT40th5DtyB8Nc56sjpATMbx8vG0KKoes7M0Kr7xWPC\n"
"pnjgJA01cnHLDBN5xU5zW2sieleFLD58NBz6A5OBxvHeJp9Kf0FU9BA9BmhHkwHo\n"
"93Pewe+LytRmjJIZnLBMJZ8s0PSQNN4hfbxmnH0ys+jhyDvSSqUbEaGq8NEWxVTe\n"
"MFSM5/961O37tkEBZfW5BZ1RdgdRNQv6GiaQMypI2UHLRJ2lAXuL7GyNPW3A5b41\n"
"y2m1iObz5jKZMh/+nCQ147OgELPVXQKe5ZV5Bb1BJ6fOL8d6RPx7iq9i\n"
"-----END CERTIFICATE-----";

/*
* PEM-encoded client private key.
*
* This is a P-256 elliptic curve key.
*/

static const char tlstestCLIENT_PRIVATE_KEY_PEM_EC[] = "-----BEGIN EC PRIVATE KEY-----\n"
"MHcCAQEEIA3Jvm6Wo9R2PoPD2gaPV6kxGCBHPS7hJNX7O8KqDOZMoAoGCCqGSM49\n"
"AwEHoUQDQgAEqGtFiBzeCj8qOeCZhw3LjS2qbGUpk7kIYM4IzvF20xLEsh8HReU0\n"
"sbspxQRvs062mkS9RBb6+h5dR36AEkx1dQ==\n"
"-----END EC PRIVATE KEY-----";

/* One character of this certificate has been changed in the issuer
 * name from Amazon Web Services to Amazon Web Cervices. */
static const char tlstestCLIENT_CERTIFICATE_PEM_MALFORMED[] = 
"-----BEGIN CERTIFICATE-----\n"
"MIIDWTCCAkGgAwIBAgIUWdsb996hKfpiA0zTKRYYZf0LZXowDQYJKoZIhvcNAQEL\n"
"BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBDZXJ2aWNlcyBPPUFtYXpvbi5jb20g\n"
"SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTE5MDMyNDA5NTg1\n"
"NFoXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0\n"
"ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMQtGaajVpsm6Njs6Doh\n"
"Cd4H1NwiqZsIN+SUQEX++Ncfnjp4aju8GRNiPeNOXRhSA11oA5BMh3IUyBMDMq9f\n"
"TNT/B7MRTsqgMsrwPnmh2CN8uRHg4He6fEg/L5ODwhsmF12YRlFKJHXqBaiePtLu\n"
"sy23l645VgIgx76Y9ibS/12pi/uQfLx1FyXDutmOWjzXU6YcLnJ0KV+wXLpYqxVA\n"
"YXwWTCx8rEuxqMAvgiPztvR9rTrU2wMvGCQnWtw/9yRO4t8yJrZM0IncdXqrVDub\n"
"bQbKhzyoYUYhgZzSj/qTX7a9/bsrBhUqea4SDmdKRFyfMX9dM8QA6adqqvx3pOtF\n"
"9J8CAwEAAaNgMF4wHwYDVR0jBBgwFoAUMxPFq1ezNaqhhXMGoLV0MbNCVAIwHQYD\n"
"VR0OBBYEFMydI9/zHorE8+TsB+3tTXaLlsAcMAwGA1UdEwEB/wQCMAAwDgYDVR0P\n"
"AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQAeO0CO0v3Z9wG/MZio92gZLFhJ\n"
"xcdN96btKkR/81pQswltYjd2N78n6+bpcvRxXAYc5LsUVx6sJpalibj4hwxCADPC\n"
"0wzED+OiW14R6O3XEX+O6HJk9RfKLjR9+VbZIVs6ZvBmt6Yy1mz+Wg58ojAWlhLc\n"
"ns8zQBpiwoKETkj3sWPUktU0UyWuTNW0Pi5ZA/AKEN1ZYfPw570brebC9winV8MU\n"
"TfXHuOe8CBgFVzmot2IjNGo0HLPFTBkZCRvTgjprHd7nyQX/TYHksqHzuM1SF9dH\n"
"wbxoNYIAbiYETyGc93uejk3Zj6ZWQyZ4n+UPhDvh8B4COkPPgsnFn6SwsM2u\n"
"-----END CERTIFICATE-----";


/* Certificate which is not trusted by the broker. */
static const char tlstestCLIENT_UNTRUSTED_CERTIFICATE_PEM[] =
"-----BEGIN CERTIFICATE-----\n"
"MIIBnTCCAUMCCQDnSd5ZLPDMQDAKBggqhkjOPQQDAjBWMQswCQYDVQQGEwJBVTET\n"
"MBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQ\n"
"dHkgTHRkMQ8wDQYDVQQDDAZjYWl4dWUwHhcNMTkwMzI2MDIzNDM5WhcNMjAwODA3\n"
"MDIzNDM5WjBXMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8G\n"
"A1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRAwDgYDVQQDDAdpdnk1NjYx\n"
"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2r/TJ8xZSU0zt4IE8jcL+EFRbG2l\n"
"CK7qf3OIfOThaJ0PHQ0PSuISKr8NnhC5drGtI4U1TKL4tPt44spD5EPqpTAKBggq\n"
"hkjOPQQDAgNIADBFAiBKnD+ZO8g06dEtcd+1p3xR6l2HMY99z+g6iILJTGjYxgIh\n"
"ALBAt5DUxKYefRhvixK0r35/xqmz+eZebihe4C9jvF6E\n"
"-----END CERTIFICATE-----";

/* Private key corresponding to the untrusted certificate. */
static const char tlstestCLIENT_UNTRUSTED_PRIVATE_KEY_PEM[] =
"-----BEGIN EC PRIVATE KEY-----\n"
"MHcCAQEEIIId4OqUE/2VipbS5YoEo5rNOAZ91T2KfLlYtbiN3KC/oAoGCCqGSM49\n"
"AwEHoUQDQgAE2r/TJ8xZSU0zt4IE8jcL+EFRbG2lCK7qf3OIfOThaJ0PHQ0PSuIS\n"
"Kr8NnhC5drGtI4U1TKL4tPt44spD5EPqpQ==\n"
"-----END EC PRIVATE KEY-----";

/* Device certificate created using BYOC instructions. */
static const char tlstestCLIENT_BYOC_CERTIFICATE_PEM[] =
    "-----BEGIN CERTIFICATE-----\n"
"MIIBnTCCAUMCCQDCPDxiUQ0zBTAKBggqhkjOPQQDAjBWMQswCQYDVQQGEwJBVTET\n"
"MBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQ\n"
"dHkgTHRkMQ8wDQYDVQQDDAZjYWl4dWUwHhcNMTkwMzI2MDIwOTM4WhcNMjAwODA3\n"
"MDIwOTM4WjBXMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8G\n"
"A1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRAwDgYDVQQDDAdpdnk1NjYx\n"
"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEScb1m+JFmzDj1Q0QCkWFe5PpfFx7\n"
"9s1+j90ZHiFAiqsWDf17+FN4PgA8fuTjnmbOEMcRJVCZn5RmBKgYdJsUsTAKBggq\n"
"hkjOPQQDAgNIADBFAiEAvohCg6W+BMxGjBCBASWr9XcUISYROXJdS3spQEPspBMC\n"
"IAmGXCouFRRSj1GxuGQm2LV+U/d9KWbUNUagxypFUuC5\n"
"-----END CERTIFICATE-----";

/* Device private key created using BYOC instructions. */
static const char tlstestCLIENT_BYOC_PRIVATE_KEY_PEM[] =
"-----BEGIN EC PRIVATE KEY-----\n"
"MHcCAQEEIMC+dX1rcZqYTH4Eu1VjVUr+e/Wl0S3N979hA2/aoxILoAoGCCqGSM49\n"
"AwEHoUQDQgAEScb1m+JFmzDj1Q0QCkWFe5PpfFx79s1+j90ZHiFAiqsWDf17+FN4\n"
"PgA8fuTjnmbOEMcRJVCZn5RmBKgYdJsUsQ==\n"
"-----END EC PRIVATE KEY-----";

#endif
#endif
